name: summarize-statistics
on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 0 1 * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API [POST] /api/statistics/summarize-day
        if: github.event.schedule == '0 0 * * *'
        run: |
          curl --request POST \
          --url 'https://ibudget-eight.vercel.app/api/statistics/summarize-day'
      - name: Call API [POST] /api/statistics/summarize-month
        if: github.event.schedule == '0 0 1 * *'
        run: |
          curl --request POST \
          --url 'https://ibudget-eight.vercel.app/api/statistics/summarize-month'
